edition = "2024"
unstable_features = true  

# Allow wider lines of code (inherit all other width settings from this)
max_width = 100
use_small_heuristics = "Default"

# Style prefs (specifying default values, incase defaults change down the line)
binop_separator = "Front"
blank_lines_lower_bound = 1
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
combine_control_expr = false
comment_width = 100
wrap_comments = true
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true
enum_discrim_align_threshold = 0
fn_params_layout = "Tall"
fn_single_line = true
force_multiline_blocks = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
hard_tabs = false
hex_literal_case = "Upper"
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
inline_attribute_width = 0
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
merge_derives = true
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = false
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
short_array_element_width_threshold = 10
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 0
struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = false

# If you write something rustfmt can't fmt then you should probably refactor
error_on_line_overflow = true  
error_on_unformatted = true
show_parse_errors = true